name: Algolia

on:
  push:
    branches:
      - master

jobs:
  algolia-index:
    name: algolia-index
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.6
          - 2.7
          - 3.0

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get Algolia to reindex
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: bundle exec jekyll algolia
